### PR TITLE
Minor corrections related to the use of `act`

### PR DESCRIPTION
**Pull request by kgregory**
## Description :memo:

The purpose of this PR is to address some very minor issues regarding the use of `act`.

- `act` is re-exported from `@testing-library/react` so it can be imported from there.  Testing library recommends importing it this way for 'consistency reasons' (see: https://testing-library.com/docs/react-testing-library/api/#act)
- You don't need to wrap `render` with `act` because it's done for you (see: https://github.com/testing-library/react-testing-library/blob/main/src/pure.js#L59-L65)

## Relevant issues :dart:

N/A

## Type of change :gem:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Refactor
 
## Example code :scroll:

```tsx
	// not this
	act(() => {
		render(<ScrollbarSizeExample />);
	});

	// this
	render(<ScrollbarSizeExample />);
``` 

## How Has This Been Tested? :vertical_traffic_light:

All tests passed

## Checklist :checkered_flag:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] New and existing unit tests pass locally with my changes
- [x] My changes pass lint, prettier, and TS checks
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by shawnmcknight** [comment]
@kgregory CI didn't run on the PR, but I think I had a setting misconfigured in CircleCI to get it to run on a PR.  Can you resubmit this and see if it gets triggered?

**Comment by kgregory** [comment]
@shawnmcknight close this out and submit a new PR?

**Comment by shawnmcknight** [comment]
> @shawnmcknight close this out and submit a new PR?

Yeah, either that or try doing a couple commits (change and change back) and push up and see if that triggers the CI run?  Circle isn't configured by default to run CI against PRs made using forks but I turned it on.  I'm hoping that was the issue.

**Comment by kgregory** [comment]
@shawnmcknight looks to have done the trick!

**Review by shawnmcknight — APPROVED** [review]
LGTM!

**Pull request merged**
